package tech.yesboss.domain.message;

import java.util.Collections;
import java.util.List;

/**
 * Unified message format for all LLM interactions.
 *
 * <p>This is the core domain entity for the LLM routing gateway module.
 * It provides an abstraction layer that decouples the system from any specific
 * vendor SDK (Claude, GPT, etc.).</p>
 *
 * <p>The record is immutable and thread-safe by design. Lists are defensively
 * copied to prevent external modification.</p>
 *
 * @param role             The message role (SYSTEM, USER, ASSISTANT, TOOL)
 * @param content          The text content (for simple text messages)
 * @param payloadFormat    The payload format identifier
 * @param toolCalls        List of tool calls initiated by the LLM (for assistant messages)
 * @param toolResults      List of tool execution results (for user/tool messages)
 * @param rawPayloadFormat The raw serialization format identifier (e.g., "ANTHROPIC_V3")
 * @param rawJsonContent   The raw JSON content for persistence and resume
 */
public record UnifiedMessage(
        Role role,
        String content,
        PayloadFormat payloadFormat,
        List<ToolCall> toolCalls,
        List<ToolResult> toolResults,
        String rawPayloadFormat,
        String rawJsonContent
) {

    /**
     * Compact constructor for defensive null checks.
     * Ensures collections are never null and are immutable.
     */
    public UnifiedMessage {
        toolCalls = toolCalls == null ? Collections.emptyList() : List.copyOf(toolCalls);
        toolResults = toolResults == null ? Collections.emptyList() : List.copyOf(toolResults);
    }

    /**
     * Simplified constructor for basic text messages.
     * Used for backward compatibility with persistence layer.
     */
    public UnifiedMessage(Role role, String content, PayloadFormat payloadFormat) {
        this(role, content, payloadFormat, Collections.emptyList(), Collections.emptyList(),
                payloadFormat.name(), content);
    }

    /**
     * Message role enum following OpenAI/Claude standards.
     */
    public enum Role {
        SYSTEM, USER, ASSISTANT, TOOL
    }

    /**
     * Payload format enum for content serialization.
     */
    public enum PayloadFormat {
        PLAIN_TEXT, ANTHROPIC_BLOCKS, OPENAI_CHATS
    }

    /**
     * Tool call initiated by the LLM.
     *
     * @param id            The unique tool call ID generated by the LLM
     * @param name          The tool name to call
     * @param argumentsJson The tool arguments as JSON string
     */
    public record ToolCall(String id, String name, String argumentsJson) {}

    /**
     * Tool execution result returned to the LLM.
     *
     * @param toolCallId    The ID of the corresponding tool call
     * @param resultString  The tool execution result (or error message)
     * @param isError       Whether this result represents an error
     */
    public record ToolResult(String toolCallId, String resultString, boolean isError) {}

    // ==========================================
    // Static Factory Methods
    // ==========================================

    /**
     * Create a simple text-only message.
     *
     * <p>This is the most common factory method, used when creating
     * user messages or system prompts.</p>
     *
     * @param role The message role (typically USER or SYSTEM)
     * @param text The text content
     * @return A new UnifiedMessage with PLAIN_TEXT format
     */
    public static UnifiedMessage ofText(Role role, String text) {
        return new UnifiedMessage(role, text, PayloadFormat.PLAIN_TEXT);
    }

    /**
     * Create a tool result message.
     *
     * <p>This is used after executing a tool to return the result
     * back to the LLM for continued processing.</p>
     *
     * @param toolCallId   The ID of the tool call this result corresponds to
     * @param result       The tool execution result
     * @param isError      Whether this result represents an error
     * @return A new UnifiedMessage with the tool result
     */
    public static UnifiedMessage ofToolResult(String toolCallId, String result, boolean isError) {
        ToolResult tr = new ToolResult(toolCallId, result, isError);
        return new UnifiedMessage(
                Role.USER, // Claude requires tool results as USER role
                result,
                PayloadFormat.PLAIN_TEXT,
                Collections.emptyList(),
                List.of(tr),
                "PLAIN_TEXT",
                result
        );
    }

    /**
     * Create a message with tool calls.
     *
     * <p>This is used when the LLM decides to call tools.</p>
     *
     * @param toolCalls The tool calls to include
     * @return A new UnifiedMessage with the tool calls
     */
    public static UnifiedMessage ofToolCalls(List<ToolCall> toolCalls) {
        return new UnifiedMessage(
                Role.ASSISTANT,
                "",
                PayloadFormat.ANTHROPIC_BLOCKS,
                toolCalls,
                Collections.emptyList(),
                "ANTHROPIC_V3",
                null
        );
    }

    /**
     * Create a system prompt message.
     *
     * @param systemPrompt The system prompt text
     * @return A new UnifiedMessage with SYSTEM role
     */
    public static UnifiedMessage system(String systemPrompt) {
        return ofText(Role.SYSTEM, systemPrompt);
    }

    /**
     * Create a user message.
     *
     * @param userText The user message text
     * @return A new UnifiedMessage with USER role
     */
    public static UnifiedMessage user(String userText) {
        return ofText(Role.USER, userText);
    }

    // ==========================================
    // Helper Methods
    // ==========================================

    /**
     * Check if this message contains tool calls.
     *
     * <p>This is used by the WorkerRunner ReAct loop to determine
     * if tools need to be executed.</p>
     *
     * @return true if the message has tool calls, false otherwise
     */
    public boolean hasToolCalls() {
        return !toolCalls.isEmpty();
    }

    /**
     * Check if this message contains tool results.
     *
     * @return true if the message has tool results, false otherwise
     */
    public boolean hasToolResults() {
        return !toolResults.isEmpty();
    }

    /**
     * Check if this is a simple text message (no tool calls or results).
     *
     * @return true if the message is text-only, false otherwise
     */
    public boolean isTextOnly() {
        return toolCalls.isEmpty() && toolResults.isEmpty();
    }

    /**
     * Get the effective content for display purposes.
     * Returns the text content, or a summary if this message contains tool calls.
     *
     * @return The displayable content
     */
    public String getDisplayContent() {
        if (!toolCalls.isEmpty()) {
            return "[Calling " + toolCalls.size() + " tool" + (toolCalls.size() > 1 ? "s" : "") + "]";
        }
        if (!toolResults.isEmpty()) {
            return "[" + toolResults.size() + " tool result" + (toolResults.size() > 1 ? "s" : "") + "]";
        }
        return content != null ? content : "";
    }
}
