package tech.yesboss.persistence.repository;

import tech.yesboss.persistence.entity.ToolExecutionLog;

import java.util.List;
import java.util.Optional;

/**
 * Repository interface for tool execution log operations.
 *
 * <p>This repository provides two types of operations:
 * <ul>
 *   <li><b>Read operations:</b> Direct SQL queries using indexes</li>
 *   <li><b>Write operations:</b> Asynchronous event submission to the SingleThreadDbWriter</li>
 * </ul>
 *
 * <p>Read operations use the following indexes:
 * <ul>
 *   <li>{@code idx_tool_log_session}: For findBySessionId()</li>
 *   <li>{@code idx_tool_log_call_id}: For findByToolCallId()</li>
 * </ul>
 */
public interface ToolExecutionRepository {

    /**
     * Find all tool execution logs for a specific session.
     *
     * <p>Used by the UI card renderer to display tool execution history.
     * Uses the {@code idx_tool_log_session} index.</p>
     *
     * @param sessionId The session ID
     * @return List of tool execution logs ordered by creation time (ascending)
     */
    List<ToolExecutionLog> findBySessionId(String sessionId);

    /**
     * Find a tool execution log by the LLM-generated tool call ID.
     *
     * <p>Uses the {@code idx_tool_log_call_id} index to trace back from
     * a tool call to the LLM thought process that triggered it.</p>
     *
     * @param toolCallId The tool call ID generated by the LLM
     * @return Optional containing the ToolExecutionLog, or empty if not found
     */
    Optional<ToolExecutionLog> findByToolCallId(String toolCallId);

    /**
     * Find all tool execution logs for a specific tool name.
     *
     * @param toolName The tool name
     * @return List of tool execution logs
     */
    List<ToolExecutionLog> findByToolName(String toolName);

    /**
     * Find all intercepted (blocked) tool executions for a session.
     *
     * @param sessionId The session ID
     * @return List of intercepted tool execution logs
     */
    List<ToolExecutionLog> findInterceptedBySession(String sessionId);

    /**
     * Asynchronously save a tool execution log.
     *
     * <p>Creates an InsertToolExecutionLogEvent and submits to the queue.
     * Called by ToolCallTracker after tool execution.</p>
     *
     * @param sessionId    The session that initiated the tool call
     * @param toolCallId   The LLM-generated tool call ID
     * @param toolName     The unified tool interface name
     * @param arguments    JSON string of arguments
     * @param result       The tool execution result or error
     * @param isIntercepted Whether the sandbox intercepted this call
     */
    void saveLog(String sessionId, String toolCallId, String toolName,
                 String arguments, String result, boolean isIntercepted);
}
